language: python

python:
  - "3.5"

services:
  - postgresql

install:
  - pip install codecov coverage pyaes psycopg2 rsa Tornado

before_script:
  - psql -c "CREATE DATABASE chat WITH ENCODING 'utf8';" -U postgres

script:
  - python3 test_processors.py
  - python3 test_request_handler.py
  - psql -c "DROP DATABASE chat" -U postgres
  - psql -c "CREATE DATABASE chat WITH ENCODING 'utf8';" -U postgres
  - coverage run test_processors.py
  - coverage run test_request_handler.py
  - coverage combine

after_success:
  - codecov

notifications:
  email: false

  slack:
    rooms:
      - owllit:GRN6KTTcUiujsRDPbBROMEr0
    on_success: always
    on_failure: always
